python exp_combining.py -m max_pool
python exp_combining.py -m max_pool_concat
python exp_combining.py -m avg_pool
python exp_combining.py -m avg_pool_concat
python exp_combining.py -m concat
python exp_combining.py -m avg_pool_max_pool
python exp_combining.py -m max_pool_avg_pool
python exp_combining.py -m concat_max_pool
python exp_combining.py -m concat_avg_pool
